### ISSUE TITLE
Switch to ActiveSupport::LogSubscriber

### ISSUE THREAD

**Issue by bdewater** [rails/solid_queue#103]
It looks like all logging is currently hardcoded. By switching to https://api.rubyonrails.org/classes/ActiveSupport/LogSubscriber.html instead (like Rails uses for most of its logging) it's easier for to change the log output - see eg https://github.com/roidrage/lograge and other Rails logging gems out there relying on this.

**Comment by rosa** [comment]
Hey @bdewater, yes, indeed! This is one of [the next things on-deck](https://github.com/basecamp/solid_queue?tab=readme-ov-file#solid-queue):
> Improvements to logging and instrumentation, a better CLI tool, a way to run within an existing process in "async" mode, unique jobs and recurring, cron-like tasks are coming very soon.

Definitely on my radar, and already started 😊

**Comment by bdewater** [comment]
That's great! Sorry I missed it in that blurb.

**Comment by rosa** [comment]
No, no worries, I realised that maybe having that there is not a great idea 😆 

I should have created separate issues for them, which I'll do now, keeping this one for the logging one.
