### ISSUE TITLE
Queue clear batching not working

### ISSUE THREAD

**Issue by ryantaylor** [rails/solid_queue#181]
Calling `SolidQueue::Queue.new(queue_name).clear` only clears the first batch of jobs and doesn't continue clearing all jobs in the queue. This is because [this line](https://github.com/rails/solid_queue/blob/main/app/models/solid_queue/execution.rb#L34) clears the `Job` records, and [these lines in the migration](https://github.com/rails/solid_queue/blob/main/db/migrate/20231211200639_create_solid_queue_tables.rb#L94-L98) cascade `DELETE`s on the `Execution` records when their associated `Job` is deleted. Therefore, once you get here, the `Execution` records have already been deleted, so `delete_all` returns `0` and execution halts instead of proceeding to the next batch.

I believe the fix is simply setting `discarded` to the return value of `discard_jobs` and dropping `where(job_id: job_ids).delete_all` altogether. I see that call is also being made elsewhere in that file (and maybe in other places) and can probably be removed in those places as well. I was going to fix it myself but it doesn't seem like executions have any tests currently and I wasn't sure how the tests were going to be organized.

**Comment by rosa** [comment]
Thanks @ryantaylor! I'll look into this.

**Comment by rosa** [comment]
Sorry for the delay and radio silence on this one! I've been working on other stuff and also travelling, but I'm back to this and I've got a fix ready that I'll be pushing together with a bunch of other changes 🙏

**Comment by rosa** [comment]
This is fixed in https://github.com/rails/solid_queue/pull/208/commits/740c20fa42f05b054d78c274cf964a4fa920608a
