### ISSUE TITLE
Does SolidQueue work with Pgbouncer in transaction mode?

### ISSUE THREAD

**Issue by vitobotta** [rails/solid_queue#187]
I am having a hard time to figure out a straight answer to this question. Can anyone help?

**Comment by rosa** [comment]
Hey @vitobotta, I'm not an expert in PostgreSQL or PgBouncer (all my professional experience has been with different MySQL flavours), but from what I understand from reading about PgBouncer transaction polling and looking [at the SQL feature map for pooling modes table](https://www.pgbouncer.org/features.html), I think it should work just fine, as we don't use any of the features that are incompatible with transaction polling.

**Comment by vitobotta** [comment]
Hi @rosa ! And thanks a lot for the clarification! I can't wait to switch to SolidQueue to simplify our stack. Thanks for confirming that it should work just fine :) I guess I can close this then. Thanks again!

**Comment by rosa** [comment]
Thank you so much! If you encounter any problems, please let me know so we can try to address them! 🙌
