### ISSUE TITLE
Job claiming erratic in Mac development

### ISSUE THREAD

**Issue by carsoncole** [rails/solid_queue#189]
It was working perfectly on my Mac in development, claiming jobs as they were submitting, but now in the console where I've executed `bundle exec rake solid_queue:start`, it stopped indicating "Claimed job.." and my jobs are not being picked up, unless I ctrl-c the console and restart, then it immediately picks up the job.

Sometimes, after retriggering and running a job, if I immediately issue another job request, it will pick it up automatically. 

No issues in production.

I've removed the `solid_queue.yml` config file to go with the defaults.  Using `solid_queue 0.3.0`. This issue cropped up after updating to this version.

**Comment by bmb1603** [comment]
Sounds like you might fill the wrong queue?

**Comment by carsoncole** [comment]
Using all defaults, no queues other than "default". It works in production. It also works on restarting the queue.

**Comment by carsoncole** [comment]
Closing this issue. Suspect there is something else going.
