### ISSUE TITLE
[Feature request] read config YAML from config/solid_queue/*.yml

### ISSUE THREAD

**Issue by ukolovda** [rails/solid_queue#220]
For ActiveStorage, I can put config file into config/storage directory.
For example, `config/storage/production.yml` (for production environment).
See https://edgeguides.rubyonrails.org/active_storage_overview.html#setup

Please, add similar feature to Solid Queue.

**Comment by rosa** [comment]
Hey @ukolovda, thanks for the suggestion! 

We're currently running Solid Queue like that as well, and we use the `SOLID_QUEUE_CONFIG` environment variable to set the path to the config. For example: 
```
SOLID_QUEUE_CONFIG=config/solid_queue/search.yml bin/rake solid_queue:work
```

would that work for you?

**Comment by ukolovda** [comment]
> Hey @ukolovda, thanks for the suggestion!
> 
> We're currently running Solid Queue like that as well, and we use the `SOLID_QUEUE_CONFIG` environment variable to set the path to the config. For example:
> 
> ```
> SOLID_QUEUE_CONFIG=config/solid_queue/search.yml bin/rake solid_queue:work
> ```
> 
> would that work for you?

Hello!

Thank you! Environment variable will be enough for me.
Sorry for bother.

**Comment by rosa** [comment]
No worries at all! 🙌
