### ISSUE TITLE
Rails 8 now requires concurrent-ruby 1.3.1 for activesupport

### ISSUE THREAD

**Issue by activefx** [rails/solid_queue#235]
Activesupport bumped concurrent-ruby requirement to at least 1.3.1 as part of [f719787](https://github.com/rails/rails/commit/f719787c582839fd2fcd886d70b43da3ddad2ceb). Will submit PR

**Comment by rosa** [comment]
This was already fixed by https://github.com/rails/solid_queue/pull/236. 🙇
