### ISSUE TITLE
Best way to delete an old queue

### ISSUE THREAD

**Issue by sebglazebrook** [rails/solid_queue#259]
Hi, I was looking at the most supported way to delete an old queue.

Something SolidQueue::Queue#delete or SolidQueue::Queue#destroy doesn't seem to exist.

Thanks!

**Comment by rosa** [comment]
Hey @sebglazebrook! Queues aren't stored anywhere, queues exist in the system as long as there are jobs enqueued in them. If you have jobs you want to get rid of for a given queue, you can do: 
```ruby
SolidQueue::Job.where(queue_name: <your queue name>).each(&:destroy)
```
You should ensure you have the foreign keys with cascade deletions created before doing this, or you might leave orphaned executions behind: 
```rb
  add_foreign_key "solid_queue_blocked_executions", "solid_queue_jobs", column: "job_id", on_delete: :cascade
  add_foreign_key "solid_queue_claimed_executions", "solid_queue_jobs", column: "job_id", on_delete: :cascade
  add_foreign_key "solid_queue_failed_executions", "solid_queue_jobs", column: "job_id", on_delete: :cascade
  add_foreign_key "solid_queue_ready_executions", "solid_queue_jobs", column: "job_id", on_delete: :cascade
  add_foreign_key "solid_queue_recurring_executions", "solid_queue_jobs", column: "job_id", on_delete: :cascade
  add_foreign_key "solid_queue_scheduled_executions", "solid_queue_jobs", column: "job_id", on_delete: :cascade
```

Alternatively you can find out in which state the jobs are, and discard these. For example, for jobs ready to be run, which is the normal case, you'd do: 
```ruby
SolidQueue::ReadyExecution.queued_as(<your queue name>).discard_all_in_batches
```

**Comment by sebglazebrook** [comment]
Thanks that worked perfectly. 

I'm not sure why but looking in mission control I should see a queue with nothing enqueued in it finding and deleting the jobs via the console worked. Thanks heaps!
