### ISSUE TITLE
urls for corresponding classes?

### ISSUE THREAD

**Issue by dorianmariecom** [rails/solid_queue#263]
i have this:

```
            div=> link_to t(".blocked_jobs", count: policy_scope(SolidQueue::BlockedExecution).size), jobs_path
            div=> link_to t(".claimed_jobs", count: policy_scope(SolidQueue::ClaimedExecution).size), jobs_path
            div=> link_to t(".failed_jobs", count: policy_scope(SolidQueue::FailedExecution).size), jobs_path
            div=> link_to t(".job_pauses", count: policy_scope(SolidQueue::Pause).size), jobs_path
            div=> link_to t(".job_processes", count: policy_scope(SolidQueue::Process).size), jobs_path
            div=> link_to t(".job_semaphores", count: policy_scope(SolidQueue::Semaphore).size), jobs_path
            div=> link_to t(".jobs", count: policy_scope(SolidQueue::Job).size), "/jobs/applications/code/finished/jobs"
            div=> link_to t(".ready_jobs", count: policy_scope(SolidQueue::ReadyExecution).size), jobs_path
            div=> link_to t(".recurring_jobs", count: policy_scope(SolidQueue::RecurringExecution).size), jobs_path
            div=> link_to t(".scheduled_jobs", count: policy_scope(SolidQueue::ScheduledExecution).size), jobs_path
```

but i'm having a hard time mapping the solid queue classes to the links in the interface

any help?

**Comment by rosa** [comment]
Hey @dorianmariecom! What are exactly these? I'm not sure what do you need exactly 🤔 What's `policy_scope` and what are these paths?

**Comment by dorianmariecom** [comment]
hey @rosa 

those are links to the /jobs path with the count of each solid queue class

e.g. <2 failed jobs>\</jobs>

what i'm wondering is how to map each solid queue class to the dashboard but thinking about it it's more of a mission_ontrol-jobs thing maybe

![Screenshot 2024-07-21 at 14  52 10](https://github.com/user-attachments/assets/0be3c6ed-c8bb-429d-90a7-46b0a462a07f)

policy_scope here (from pundit, an authorization gem) is just `policy_scope(Job)` == `Job.all` so i'm doing `Job.size`

this would also help me because I would like to manually manage those jobs in the database so understanding them would help

**Comment by rosa** [comment]
Oh 🤔  Hmmm... would looking at [Mission Control Jobs code help here](https://github.com/rails/mission_control-jobs/tree/main/app/controllers/mission_control/jobs)? Or [the Solid Queue extension in Mission Control Jobs](https://github.com/rails/mission_control-jobs/blob/main/lib/active_job/queue_adapters/solid_queue_ext.rb). Counting some of these classes might not be relevant, for example, `SolidQueue::Semaphore`. Recurring jobs aren't directly `recurring_executions` either, and workers are a subset of processes 🤔

**Comment by dorianmariecom** [comment]
thx, i get a better view of how this works

i ended doing:

```
            div=> link_to t(".blocked_jobs", count: policy_scope(SolidQueue::BlockedExecution).size), "/jobs/applications/code/blocked/jobs"
            div=> link_to t(".claimed_jobs", count: policy_scope(SolidQueue::ClaimedExecution).size), jobs_path
            div=> link_to t(".failed_jobs", count: policy_scope(SolidQueue::FailedExecution).size), "/jobs/applications/code/failed/jobs"
            div=> link_to t(".job_pauses", count: policy_scope(SolidQueue::Pause).size), jobs_path
            div=> link_to t(".job_processes", count: policy_scope(SolidQueue::Process).size), jobs_path
            div=> link_to t(".job_semaphores", count: policy_scope(SolidQueue::Semaphore).size), jobs_path
            div=> link_to t(".jobs", count: policy_scope(SolidQueue::Job).size), "/jobs/applications/code/finished/jobs"
            div=> link_to t(".ready_jobs", count: policy_scope(SolidQueue::ReadyExecution).size), jobs_path
            div=> link_to t(".recurring_jobs", count: policy_scope(SolidQueue::RecurringExecution).size), "/jobs/applications/code/recurring_tasks"
            div=> link_to t(".scheduled_jobs", count: policy_scope(SolidQueue::ScheduledExecution).size), "/jobs/applications/code/scheduled/jobs"
```
