### ISSUE TITLE
SolidQueue trying to interact with db2 database connection and failing to insert job records

### ISSUE THREAD

**Issue by Naren1997** [rails/solid_queue#266]
Hello Team,

We have two DB connections in our project, one is for storing data in our Postgres DB, another connection is for IBM DB2, which has the actual data in it, we get the data from DB2 and puts in our Postgres DB. When I'm trying to integrate SolidQueue, I see a weird error, when I'm trying to insert a record to solid_queue_jobs table from rails console, I get the following error from ibm_db2 gem, but I have specified solidqueue to make use of postgres. Except Insert query all other queries are working fine. I don't know why insert query in the first place trying to interact with ibm_db2 gem code.

`        puts_log "create_savepoint"
        ^^^^^^^^)
/home/user/.rvm/gems/ruby-3.1.2/gems/ibm_db-5.4.1/lib/active_record/connection_adapters/ibm_db_adapter.rb:383:in `create_savepoint': undefined method `puts_log' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007f406072af40 @transaction_manager=#<ActiveRecord::ConnectionAdapters::TransactionManager:0x00007f40607316d8 @stack=[], @connection=#<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007f406072af40 ...>, @has_unmaterialized_transactions=false, @materializing_transactions=false, @lazy_transactions_enabled=true>, @query_cache={}, @query_cache_enabled=false, @connection=#<PG::Connection:0x00007f4060722e30 host=localhost port=5432 user=postgres type_map_for_results=#<PG::TypeMapByOid:0x00007f40606cef60> type_map_for_queries=#<PG::TypeMapByClass:0x00007f40606c1040>>, @owner=#<Thread:0x00007f4075e6bce0 run>, @instrumenter=#<ActiveSupport::Notifications::Instrumenter:0x00007f4060539c90 @id="859a0b8d46e5da3174ae", @notifier=#<ActiveSupport::Notifications::Fanout:0x00007f40701df7b0 @string_subscribers={"service_upload.active_storage"=>[#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bdfc0 @pattern="service_upload.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 @queue_key="ActiveStorage::LogSubscriber-4980", @patterns={"service_upload.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bdfc0 ...>, "service_download.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc800 @pattern="service_download.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_streaming_download.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc738 @pattern="service_streaming_download.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_delete.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc670 @pattern="service_delete.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_delete_prefixed.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc5a8 @pattern="service_delete_prefixed.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_exist.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc2d8 @pattern="service_exist.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_url.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc170 @pattern="service_url.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_mirror.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc0a8 @pattern="service_mirror.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>}>, @can_publish=false, @can_publish_event=true>], "service_download.active_storage"=>[#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc800 @pattern="service_download.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 @queue_key="ActiveStorage::LogSubscriber-4980", @patterns={"service_upload.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bdfc0 @pattern="service_upload.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_download.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc800 ...>, "service_streaming_download.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc738 @pattern="service_streaming_download.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_delete.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc670 @pattern="service_delete.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_delete_prefixed.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc5a8 @pattern="service_delete_prefixed.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_exist.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc2d8 @pattern="service_exist.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_url.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc170 @pattern="service_url.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>, "service_mirror.active_storage"=>#<ActiveSupport::Notifications::Fanout::Subscribers::Evented:0x00007f40701bc0a8 @pattern="service_mirror.active_storage", @delegate=#<ActiveStorage::LogSubscriber:0x00007f40701beb50 ...>, @can_publish=false, @can_publish_event=true>}>, @can_publish=false, @can_publish_event=true>], etc....`

environment usage
ruby 3.1.2
rails 7.0.8
postgres14.3
pg gem version 1.5.5
ibm_db gem version 5.4.1
solid_queue 0.1.2

config.solid_queue.connects_to = { database: { writing: :primary, reading: :primary } }

database.yml
default: &default
  primary:
    adapter: postgresql
    schema_search_path: 'blueid'
  db2_source:
    database_tasks: false
    adapter: ibm_db
    schema: blueid
    encoding: utf8

Any help with debugging this is greatly appreciated!

**Comment by rosa** [comment]
Huh, this is very strange 😕  I'm not sure I understand the logs very well. I see this error: 
```
undefined method puts_log' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter
```
Is it because the `ibm_db` adapter is using a PostgreSQL adapter under the hood? 

One thing, before we dig deeper: could you upgrade Solid Queue to the latest version? 0.3.4. You might need to run some extra migrations for that.

**Comment by rosa** [comment]
Another thing that might help is to try to enqueue a job with `ActiveRecord::Base.logger.level = :debug` in your console, and include the full logs from the job insertion, no need to include the whole `ctiveRecord::ConnectionAdapters::PostgreSQLAdapter` object, which is pretty big.

**Comment by rosa** [comment]
Thanks @Naren1997! 🙏  Going to check these and will let you know.

**Comment by rosa** [comment]
Hey @Naren1997, would you mind copying the output of 
```ruby
SolidQueue::Job.connection.raw_connection
```
from your development console? I think that'll confirm the PostgreSQL adapter is being used 🤔 

From the full logs, looks like the `INSERT` is at least happening on PostgreSQL:
```sql
INSERT INTO "solid_queue_jobs" ("queue_name", "class_name", "arguments", "priority", "active_job_id", "scheduled_at", "finished_at", "concurrency_key", "created_at", "updated_at") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"
```
because I don't think IBM DB2 supports [`RETURNING`](https://www.postgresql.org/docs/current/dml-returning.html). However, the `ibm_db` adapter is somehow being mixed with that, how puzzling! The `create_savepoint` method is being called because there's a callback on `SolidQueue::Job`: after creating the job we prepare it for execution, which creates other records. The `update` operation doesn't trigger any callbacks, thus no save points, and no errors. 

Do you have any models in your app that trigger any callbacks before/after saving to save other models? Wondering if you could test with those and see if the same thing happens. 

I think GoodJob doesn't run any callbacks when inserting jobs so that might be a reason this is not happening, but I'm not sure.

**Comment by Naren1997** [comment]
Hello @rosa Yeah I noticed for other models if I have a callback that has the logic to call the create_savepoint it is giving the same error. It look the issue is with the ibm_db2 package, they have written this https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/lib/active_record/connection_adapters/ibm_db_adapter.rb#L502 code such that it'll override the actual https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract/savepoints.rb#L6

I'll open an issue with ibm_db2. 

Thank you much for your support!

**Comment by Naren1997** [comment]
Issue is with ibm_db2 package

**Comment by rosa** [comment]
Aha! Great catch! Thanks a lot for letting me know, this can be helpful in the future in case someone else runs into this 🙏
