### ISSUE TITLE
Best way to delete finished jobs

### ISSUE THREAD

**Issue by initseis** [rails/solid_queue#278]
Hi, I’d like to know how to delete finished jobs to free up space in my database. What’s the best way to do this?

Thanks in advance.

**Comment by rosa** [comment]
Hey @initseis, you can rely on 

> `clear_finished_jobs_after`: period to keep finished jobs around, in case `preserve_finished_jobs` is true—defaults to 1 day. **Note**: Right now, there's no automatic cleanup of finished jobs. You'd need to do this by periodically invoking `SolidQueue::Job.clear_finished_in_batches`. 

You can do that as a one-off clean up or you can also have a periodic recurring job that runs that.

**Comment by initseis** [comment]
> Hey @initseis, you can rely on
> 
> > `clear_finished_jobs_after`: period to keep finished jobs around, in case `preserve_finished_jobs` is true—defaults to 1 day. **Note**: Right now, there's no automatic cleanup of finished jobs. You'd need to do this by periodically invoking `SolidQueue::Job.clear_finished_in_batches`.
> 
> You can do that as a one-off clean up or you can also have a periodic recurring job that runs that.

Thanks @rosa. Appreciate the guidance!

**Comment by coorasse** [comment]
Update on that: https://github.com/rails/solid_queue/commit/6437617966bc5bf92995986fc1b14e00f8c68848
