### ISSUE TITLE
Terribly long and infinite error logs when crashed

### ISSUE THREAD

**Issue by danwetherald** [rails/solid_queue#279]
Why are the errors impossibly long and infinite when there is a crash, the logs also almost provide zero value.

```
bundle exec rake solid_queue:start
/Users/danwetherald/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/pg-1.5.7/lib/pg/connection.rb:703: /Users/danwetherald/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/pg-1.5.7/lib/pg/connection.rb:703: [BUG] [BUG] Segmentation fault at 0x00000001203a0b0aSegmentation fault at 0x00000001203a0b0a
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]


ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]

-- Crash Report log information ---------------------------------------------- Crash Report log information --------------------------------------------
   See Crash Report log file in one of the following locations:
     See Crash Report log file in one of the following locations:
       * ~/Library/Logs/DiagnosticReports
       * ~/Library/Logs/DiagnosticReports
      * /Library/Logs/DiagnosticReports
       * /Library/Logs/DiagnosticReports

   for more details.   for more details.                                                                           

Don't forget to include the above Crash Report log file in bug reports.Don't forget to include the above Crash Report log file in bug reports.
```

This is followed by the worlds longest stack trace.

In this example, I am assuming something is wrong with the database connection...?

**Comment by rosa** [comment]
Hey @danwetherald! This error is not happening in Solid Queue, it's happening in the `pg` gem. It's [a segmentation fault](https://en.wikipedia.org/wiki/Segmentation_fault), which wouldn't generally happen unless the gem includes C extensions or unless there's a bug in Ruby itself. These crash reports are generated by Ruby and have nothing to do with Solid Queue. 

If you're running this on macOS, I think the following might help: https://github.com/rails/solid_queue/issues/145.
