### ISSUE TITLE
About shutdown judgment of Worker Process

### ISSUE THREAD

**Issue by tmimura39** [rails/solid_queue#282]
Hi, I am currently trying to get SolidQueue support for the [job-iteration gem](https://github.com/Shopify/job-iteration). https://github.com/Shopify/job-iteration/issues/496

A brief description of job-iteration is as follows
> Meet Iteration, an extension for [ActiveJob](https://github.com/rails/rails/tree/main/activejob) that makes your jobs interruptible and resumable, saving all progress that the job has made (aka checkpoint for jobs).

[iteration-how-it-works](https://github.com/Shopify/job-iteration/blob/fc0191c60b17f26360442e52b61276361a11f09e/guides/iteration-how-it-works.md)

Here is what needs to be addressed for each Adapter.
> The job iterates over two records of the relation and then receives SIGTERM (graceful termination signal) caused by a deploy.
> The signal handler sets a flag that makes job_should_exit? return true.

I want to determine if the SolidQueue Worker Process is about to receive a `TERM` and shutdown.

Is this judgment correct?
```ruby
# frozen_string_literal: true

begin
  require "solid_queue"
rescue LoadError
  # SolidQueue is not available, no need to load the adapter
  return
end

module JobIteration
  module InterruptionAdapters
    module SolidQueueAdapter
      class << self
        attr_accessor :stopping

        def call
          stopping
        end
      end
    end

    ActiveSupport::Notifications.subscribe("graceful_termination.solid_queue") do
      JobIteration::Integrations::SolidQueueAdapter.stopping = true
    end

    register(:solid_queue, SolidQueueAdapter)
  end
end
```

GoodJob has implemented a new feature for this.
https://github.com/bensheldon/good_job/pull/1253

I would appreciate your advice as I am unable to determine if the same action is required for SolidQueue.

**Comment by rosa** [comment]
I had completely forgotten that @bdewater had commented about Shopify's job-iteration in https://github.com/rails/solid_queue/issues/124#issuecomment-1989708846, with some quite helpful insight: 

> It interacts in various ways with background queues: it uses the Sidekiq [`quiet` callback](https://github.com/sidekiq/sidekiq/wiki/Deployment#events), GoodJob recently added `current_thread_shutting_down?` to query for this, and for Resque a monkey patch is used.

> IMO a callback is a bit more flexible since for other use cases one might not be able to/want to poll for this.

I'm going to look into providing a callback like Sidekiq as well.

**Comment by rosa** [comment]
Thanks for your patience! I've added a couple of lifecycle hooks, `start` and `stop`, in #317. Do you think this could work to add an adapter that would be quite similar to [the Sidekiq adapter](https://github.com/Shopify/job-iteration/blob/b2f31c2747d1878344d2a0b324a74950ddecdc7e/lib/job-iteration/interruption_adapters/sidekiq_adapter.rb#L10-L29)?

**Comment by tmimura39** [comment]
Thanks!

That is a very good mechanism, but it may not be available for job-iteration.
In `job-iteration`, we want to detect the receipt of a `TERM` signal in the process that actually processes the job (i.e., the Worker in SolidQueue).

Its lifecycle hooks (https://github.com/rails/solid_queue/pull/317) are executed only in the Supervisor process.

When the Supervisor receives a TERM signal, it sends a TERM signal to the fork process including the Worker.
https://github.com/rails/solid_queue/blob/a17a08b70d5904d9386019d72207de19e5340fb6/lib/solid_queue/supervisor.rb#L97

It would be nice to be able to set some kind of hook when this TERM signal is received in the Worker process.

---

On second thought, `ActiveSupport::Notifications.subscribe(“graceful_termination.solid_queue”)` was still insufficient.

The “graceful_termination.solid_queue” event is fired only in the Supervisor process, so it seems that the Worker process cannot detect it.


Please point out any errors in my perception.

**Comment by rosa** [comment]
Ah yes! You're right! I hadn't thought very well about this on the job-iteration gem; I was following the idea of subscribing to the `graceful_termination.solid_queue` event that as you said, is only fired in the supervisor. 

I'll tweak this!

**Comment by rosa** [comment]
Ok, I've got `on_worker_stop` now, added in https://github.com/rails/solid_queue/pull/317/commits/18f89e5db441b0b13843a789f4a8fceda1827550. I think this one should work!

**Comment by tmimura39** [comment]
Excellent👍 

Just what I wanted.
I was able to confirm that it works correctly in combination with job-iteration.

Thank you so much!

**Comment by rosa** [comment]
Awesome! Thanks a lot. I'll merge this and release a new version with these changes 🙏

**Comment by rosa** [comment]
Done! Version 0.7.1 has these new hooks. Going to close this one then, but let me know if you encounter any problems 🙏  Thanks again for the patience and help!
