### ISSUE TITLE
Are SolidQueue models part of the "public API"?

### ISSUE THREAD

**Issue by ibrahima** [rails/solid_queue#285]
I just realized that one thing that's neat about SolidQueue is that since it's using ActiveRecord we can query tables using normal ActiveRecord methods. However, I was wondering, is this part of the "pbulic API"/intended usage? E.g. [Sidekiq has an API](https://github.com/sidekiq/sidekiq/wiki/API) for querying queues and things. I was trying to figure out how to do it with SolidQueue and realized we can just query the tables directly... but I'm wondering if it's safe to build functionality that depends on this?

Thanks!

**Comment by rosa** [comment]
Hey @ibrahima, good question! Yes, they should be mostly part of the public API. [We use these in Mission Control](https://github.com/rails/mission_control-jobs/blob/7f71ec89b6213361e29dbc985495b5b8f473d995/lib/active_job/queue_adapters/solid_queue_ext.rb) so I think that's a good starting point for what you can expect to be stable.

**Comment by ibrahima** [comment]
Thank you! That's good to know!

As an aside, it would be nice if ActiveJob had an API for querying jobs but I can work with SolidQueue directly for now. But if it was part of ActiveJob then potentially I could use it with the test adapter, whereas for now for things where I need to use the SolidQueue models I have to use that adapter in the tests.

**Comment by rosa** [comment]
> As an aside, it would be nice if ActiveJob had an API for querying jobs but I can work with SolidQueue directly for now. But if it was part of ActiveJob then potentially I could use it with the test adapter

Totally! This is what Mission Control does, [it offers an API for querying jobs](https://github.com/rails/mission_control-jobs?tab=readme-ov-file#console-helpers-scripting-and-dealing-with-big-sets-of-jobs). I hope we can upstream this to Active Job in the future 🤞

**Comment by ibrahima** [comment]
Oh snap, I didn't realize that was there. I could definitely use that to make things more generic... Will have to check that out.
