### ISSUE TITLE
Feature Request: create separate rake tasks solid_queue:dispatch and solid_queue:work

### ISSUE THREAD

**Issue by doctomarculescu** [rails/solid_queue#296]
Hi team solid_queue,

Currently it is only possible to start solid queue by the command `bundle exec rake solid_queue:start`. This is implemented in the file https://github.com/rails/solid_queue/blob/main/lib/solid_queue/tasks.rb#L3.

The start task loads the configuration file `solid_queue.yml` and according to the sections described in the configuration (dispatchers and workers) it starts all the processes. I am not able to start dispatchers and workers separately from the same repository, because I only have a single configuration file. From my testing it turns out at high job execution rates it is important for performance that the dispatchers dispatch batches at a constant rate, while workers auto scale depending on the ready jobs. 

I would like to have two different rake tasks `bundle exec rake solid_queue:dispatch` and `bundle exec rake solid_queue:work` that start only dispatchers respectively only workers. Something along the lines:

```
namespace :solid_queue do
  desc "start solid_queue supervisor to dispatch and process jobs"
  task start: :environment do
    SolidQueue::Supervisor.start
  end

  desc "start solid_queue supervisor to dispatch jobs"
  task dispatch: :environment do
    SolidQueue::Supervisor.start_dispatchers
  end

  desc "start solid_queue supervisor to process jobs"
  task work: :environment do
    SolidQueue::Supervisor.start_workers
  end
end
```

If there is any existing workaround that would allow one to separately start dispatchers and workers from the same repository, I would be happy to hear about it. I am also more than happy to contribute with a PR if the feature request is validated.

Many thanks!

Andrei

**Comment by rosa** [comment]
Hey Andrei! This changed about a month ago in https://github.com/rails/solid_queue/pull/269 to make things simpler. You can provide a different configuration file via the `SOLID_QUEUE_CONFIG` environment variable (I plan to build a better CLI that would accept that as an option, but for now this is the way), so you can have something like: 
```
SOLID_QUEUE_CONFIG=config/solid_queue/dispatcher.yml bundle exec rake solid_queue:start
```
And then in `config/solid_queue/dispatcher.yml` you provide configuration for `dispatchers` only. This is what we currently do.

**Comment by doctomarculescu** [comment]
thank you  @rosa
