### ISSUE TITLE
Support for instrumenting polling?

### ISSUE THREAD

**Issue by gjtorikian** [rails/solid_queue#311]
Hello! I was wondering if you'd accept a PR that implements instrumentation around polling. Something pretty much like this:

```ruby
def with_polling_volume(&block)
  SolidQueue.instrument(:polling) do
    if SolidQueue.silence_polling? && ActiveRecord::Base.logger
      ActiveRecord::Base.logger.silence(&block)
    else
      yield
    end
  end
end
```

The reason being that even though `silence_polling` silences log statements, it does not silence instrumentation. That means that if the Rails app is hooked up to (for example) OpenTelemetry, the monitoring system receives thousands of `BEGIN` / `COMMIT` statements signifying nothing more than the polling is being checked. Can you tell when SQ was deployed? :P 

![graf](https://github.com/user-attachments/assets/b2289b02-705c-4745-9ba9-33262f529535)

Currently, I have a monkey patch to support ignoring this:

```ruby
module SolidQueue
  module Processes
    module PollerExtension
      def with_polling_volume
        OpenTelemetry::Instrumentation::PG.with_attributes("polling.solid_queue" => "true") do
          super
        end
      end
    end
  end
end

require "solid_queue/processes/poller_extension"

SolidQueue::Processes::Poller.prepend(SolidQueue::Processes::PollerExtension)
```

I can then instruct my collector to just filter out any `polling.solid_queue` events. This works, but it would be nice to remove my hack. 😆

**Comment by gjtorikian** [comment]
No worries!

**Comment by gjtorikian** [comment]
If anyone in the future comes here, the solution is now:

```ruby
ActiveSupport::Notifications.subscribe("polling.solid_queue") do
  OpenTelemetry::Trace.current_span.add_attributes({
    "polling.solid_queue" => "true",
  })
end
```

I hope your world is nice.

**Comment by timwis** [comment]
@gjtorikian Would you mind clarifying where you put that snippet? When I try it, there is no current_span. Wondering if perhaps it's just outdated? I'm also getting a ton of noise in my tracing system.

**Comment by gjtorikian** [comment]
I placed it into `config/initializers/solid_queue.rb`. [`current_span`](https://github.com/open-telemetry/opentelemetry-ruby/blob/4834e0056e877019ef266a852ba24f96e36f194f/api/lib/opentelemetry/trace.rb#L48-L51) is also still present in `main` for the OTel gem.

Edit: the other half of this is updating your OTel configuration. We want the processor to ignore any traces tagged with `polling.solid_queue`:

```yaml
processors:

  filter/ignoredbops:
    error_mode: ignore
    traces:
      span:
        - 'IsMatch(attributes["polling.solid_queue"], "true")'

service:

    traces:
      processors: [filter/ignoredbops]
```

**Comment by jamesiarmes** [comment]
@gjtorikian can you verify that this is working as intended? I'm trying to add it to my app, but it looks like the event fires too late. `OpenTelemetry::Trace.current_span` is returning a non-recording span. Is this expected?

**Comment by gjtorikian** [comment]
Yes, I have verified it, they're not showing up in my Honeycomb logs. I'm not sure what else I can do to offer help. Instrumentation depends on a variety of factors. My `opentelemetry-sdk` is `1.8.0` if that helps.
