### ISSUE TITLE
Same database for queue

### ISSUE THREAD

**Issue by lethaale** [rails/solid_queue#328]
Hi @rosa!

I want to deploy a single database with both normal data and solid queue data and I can't find in the README how.

Can you help? Thanks in advance!

**Comment by dhh** [comment]
Take the contents of the queue_schema.rb file, shove it into a migration, and remove the "config.solid_queue.connects_to" line from config/environments/production.rb 👍

**Comment by lethaale** [comment]
Thanks @dhh! 
Same goes for Solid Cache, I assume? 
Do you want me do a PR and add it to README?

**Comment by rosa** [comment]
> Same goes for Solid Cache, I assume?

Yes!

> Do you want me do a PR and add it to README?

That'd be super nice if you have time 🙏 😊
