### ISSUE TITLE
Customize the parent class of SolidQueue::RecurringJob

### ISSUE THREAD

**Issue by tmimura39** [rails/solid_queue#356]
## Introduction

[Allow specifying recurring tasks just with a "command"
](https://github.com/rails/solid_queue/commit/90f63c8a776a58c276ab34fd5b904e20051f550a)
I find this feature very interesting.

However, there is one barrier to its use.
That is, the parent of `SolidQueue::RecurringJob` is fixed at `ActiveJob::Base`.

I have defined error handling in ApplicationJob as described below.
https://github.com/rails/solid_queue/blob/67b964d5e9d1120e0f198dc1ef538a0aff966133/README.md#error-reporting-on-jobs

This error handling does not work when using “command”.

## Proposal

How about allowing customization of the `SolidQueue::RecurringJob` parent class?

Thinking something similar to `MaintenanceTasks.parent_controller`.
https://github.com/Shopify/maintenance_tasks/blob/d98544fb3de714a14082b64e6831980945db01cf/README.md#customizing-the-parent-controller-for-the-web-ui

What do you think?

## Workaround

Just extend SolidQueue::RecurringJob.

```ruby
module JobErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from(Exception) do |exception|
      Rails.error.report(exception)
      raise exception
    end
  end
end

class ApplicationJob < ActiveJob::Base
  include JobErrorHandling
end

Rails.application.config.after_initialize do
  SolidQueue::RecurringJob.include(JobErrorHandling)
end
```

**Comment by rosa** [comment]
Yes, good idea! I'll get this done shortly. I could also allow providing the job class to be used in this case 🤔  Like [`config.action_mailer.delivery_job`](https://guides.rubyonrails.org/configuring.html#config-action-mailer-delivery-job).

**Comment by tmimura39** [comment]
I just noticed that you already have the ability to customize a job class 👀 
(I don't know if this is an official config 🙃)
```ruby
Rails.application.config.after_initialize do # or to_prepare
  SolidQueue::RecurringTask.default_job_class = MyRecurringCommandJob
end
```

**Comment by rosa** [comment]
Oh wow, yes, it is! 🤣  I added this ages ago when I first started implementing this feature. Then, I had to work on other non-solid queue stuff at work, and came back to it recently. I had completely forgotten I had added that! 🤣 I also forgot to expose it or document it 😅  I think this could work! My initial idea was to also allow people to do different things with their `command` parameter.

**Comment by rosa** [comment]
So sorry for the delay! 😳 I completely forgot about this 🙈 I've just documented the `default_job_class` option that was completely undocumented 😅

**Comment by rosa** [comment]
@nimmolo yes! You can totally use that 😊
