### ISSUE TITLE
Recurring schedule is not deleting removed tasks

### ISSUE THREAD

**Issue by majkelcc** [rails/solid_queue#359]
Tasks deleted from `config/schedule.yml` are not being removed from the schedule.

**Comment by rosa** [comment]
Hey @majkelcc, is this https://github.com/rails/solid_queue/issues/310, or are actually deleted tasks still being run?

**Comment by majkelcc** [comment]
Hi @rosa, that's it! All makes sense when dealing with multiple dispatchers. After dealing with the other issues around recurring configuration I forgot to scan previous issues for this. Maybe it's worth it to add a note in README on how this works currently?

**Comment by rosa** [comment]
I'm going to change it so that a single scheduler is allowed to simplify things, so yes, I'll add a note in the README about it and will also delete previous tasks.

**Comment by jwald1** [comment]
Is removing a job from recrring.yml supposed to delete the job? I tried it, but it didn’t seem to work. Just for context, I’m using the latest versions of mission_control and sold_queue.

**Comment by rosa** [comment]
@jwald1, what do you mean by "delete the job"? That it disappears from the recurring tab in Mission Control? That if there's an execution in progress, it stops? If the first, yes, if the second, no.

**Comment by jwald1** [comment]
Thanks, @rosa. I mean, "That it disappears from the recurring tab in Mission Control."

**Comment by rosa** [comment]
Aha, then it should be removed once you restart the scheduler so it picks the new configuration in `recurring.yml`. Normally that would happen as part of the deployment that you'd need to update the file itself.  It's that not happening for you? 🤔
