### ISSUE TITLE
Install command failed in Rails 7.0

### ISSUE THREAD

**Issue by masterT** [rails/solid_queue#363]
Running the install steps failed in Rails 7.0 application.

```bash
bin/rails solid_queue:install
```

```
rails aborted!
Don't know how to build task 'solid_queue:install' (See the list of available tasks with `rails --tasks`)
Did you mean?  solid_queue:start

(See full trace by running task with --trace)
```

I think the correct command is `bin/rails generate solid_queue:install` has it's a generator:

```bash
bin/rails generate -h
```

```
Usage: rails generate GENERATOR [args] [options]

General options:
  -h, [--help]     # Print generator's options and usage
  -p, [--pretend]  # Run but do not make any changes
  -f, [--force]    # Overwrite files that already exist
  -s, [--skip]     # Skip files that already exist
  -q, [--quiet]    # Suppress status output

Please choose a generator below.

[...]

SolidQueue:
  solid_queue:install
```

**Comment by rosa** [comment]
Hey @masterT, what version of Solid Queue are you trying this with?

**Comment by masterT** [comment]
Hum, I followed the instruction `bundle add solid_queue`, I did not realise that since my application is using rails `'~> 7.0.8.4'` bundler installed `gem 'solid_queue', '~> 0.1.2'`.

**Comment by masterT** [comment]
I tested and used `rails solid_queue:install` with a brand new rails `>= 7.1` and it worked. I guess I will need to upgrade my Rails application 🙃.

**Comment by rosa** [comment]
Ahh, great to know! 🙏  Yes, `solid_queue` requires Rails >= 7.1, and the command `solid_queue:install` was added in a newer version.
