### ISSUE TITLE
[_J_L_M_] Please Add Support JRuby

### ISSUE THREAD

**Issue by ddd2283** [rails/solid_queue#374]
me$ jruby -S bundle exec bin/rake  solid_queue:start

The signal QUIT is in use by the JVM and will not work correctly on this platform

rake aborted!

NotImplementedError: fork is not available on this platform
/home/sbc_dev/jruby_gems/gems/solid_queue-0.1.2/lib/solid_queue/supervisor.rb:122:in `start_fork'
/home/sbc_dev/jruby_gems/gems/solid_queue-0.1.2/lib/solid_queue/supervisor.rb:72:in `block in start_forks'
/home/sbc_dev/jruby_gems/gems/solid_queue-0.1.2/lib/solid_queue/supervisor.rb:72:in `start_forks'
/home/sbc_dev/jruby_gems/gems/solid_queue-0.1.2/lib/solid_queue/supervisor.rb:45:in `supervise'
/home/sbc_dev/jruby_gems/gems/solid_queue-0.1.2/lib/solid_queue/supervisor.rb:26:in `start'
/home/sbc_dev/jruby_gems/gems/solid_queue-0.1.2/lib/solid_queue/supervisor.rb:14:in `start'
/home/sbc_dev/jruby_gems/gems/solid_queue-0.1.2/lib/solid_queue/tasks.rb:4:in `block in <main>'
org/jruby/ext/monitor/Monitor.java:82:in `synchronize'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/lib/bundler/cli/exec.rb:23:in `run'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/lib/bundler/cli.rb:455:in `exec'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/lib/bundler/cli.rb:35:in `dispatch'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/lib/bundler/cli.rb:29:in `start'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/exe/bundle:28:in `block in <main>'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/sbc_dev/jruby_gems/gems/bundler-2.5.17/exe/bundle:20:in `<main>'
uri:classloader:/META-INF/jruby.home/bin/bundle:25:in `<main>'
Tasks: TOP => solid_queue:start
(See full trace by running task with --trace)

**Comment by rosa** [comment]
Hey! Just like with Windows (https://github.com/rails/solid_queue/issues/81), this is not currently something we have planned to address. Maybe if we add a mode to run the supervised processes in the same process... but it's not currently planned.

**Comment by headius** [comment]
I would like to help make this happen!

JRuby does not support fork, but it can easily run multiple isolated JRuby instances in a single process, if that's necessary.

I am not familiar with this library, however, and I'm not sure why forking is used here. Perhaps you can explain and I could try to find an alternative for you?

**Comment by rosa** [comment]
Hey @headius, thank you! Solid Queue is a DB-based queuing backend for [Active Job](https://edgeguides.rubyonrails.org/active_job_basics.html). Workers (and other agents) run as different processes to achieve parallelism. 

I think the way to support JRuby would be to have an "async" mode (I've called it that way, but it's not the best name, arguably) where everything uses the same process. I had that implemented long ago, but it was decided to scrap it from the final release for simplification purposes. I might try to bring it back at some point.
