### ISSUE TITLE
Should delete the old recurring task when the task changed key, or removed

### ISSUE THREAD

**Issue by iuhoay** [rails/solid_queue#382]
When the key of a recurring task is changed or the task is removed, should the old task be automatically deleted? This is to ensure that outdated tasks do not continue to run.

**Comment by brettallred** [comment]
I was wondering the same thing. 

We had a recurring task defined in recurring.yml. After deploy it began running on the regular schedule. 
I added three more recurring tasks and removed the original task. However, in the recurring tasks, it is still being executed.

I'm about to look into the internals now, but I'm assuming that the yml file is being read and creating records in the DB. We probably need to remove the DB entry manually for now but wondering if this is a known issue.

**Comment by rosa** [comment]
Hey! Are you sure the removed task is still running or just listed in Mission Control but not running? See
- https://github.com/rails/solid_queue/issues/359
- https://github.com/rails/solid_queue/issues/310

**Comment by iuhoay** [comment]
Got it, thanks a lot! @rosa

**Comment by antulik** [comment]
@rosa I can confirm the removed task is indeed running.

**Comment by rosa** [comment]
@antulik how can you confirm this? Do you have examples of `solid_queue_recurring_executions` records created after you've deleted the task from the config and redeployed, restarting the processes?

**Comment by antulik** [comment]
My apologies, I didn't look deep enough. Execution is not scheduled. To be more specific for a removed cron task:

- Mission Control -> Recurring tasks -> Next: column **IS** updated 
- Mission Control -> Recurring tasks -> Last enqueued: column is **NOT** updated 
- Job execution is **NOT** scheduled

 Updated `Next` column threw me off as I expected it to not change as well. TIL

**Comment by rosa** [comment]
Ahhh, makes sense. I'm going to fix this confusion in any case very soon, making sure recurring tasks that are removed from the config are also removed from the DB.

**Comment by rosa** [comment]
Actually going to reopen this one to track that.
