### ISSUE TITLE
Relax Rails requirement (to 7.0)?

### ISSUE THREAD

**Issue by codealchemy** [rails/solid_queue#386]
Hi there 👋 , we're in the process of migrating quite a few jobs to ActiveJob, most use Resque - but a good amount are using [the `resque-durable` gem](https://github.com/zendesk/resque-durable) to solve many of the same problems that SolidQueue was built for, and we'd like to consider using this adapter instead.

We're _also_ in the process of migrating to more recent Rails releases, but are currently on 7.0.

Following https://github.com/rails/solid_queue/pull/94, Rails >= 7.1 has been required for this project - would you be open to relaxing the Rails restriction to 7.0 (which isn't yet EOL)? Or is there more than the serialization that would cause issue?

**Comment by dhh** [comment]
I think you're better off just doing a private fork, applying those changes, and then use that until you're ready to upgrade the Rails version to something compatible with Solid Queue's default path.
