### ISSUE TITLE
Usage of schema_format = :sql

### ISSUE THREAD

**Issue by jherdman** [rails/solid_queue#394]
Greetings!

I'm still all hopped up on those sweet sweet Rails World vibes, and am presently writing a SQLite powered Rails app.

I'm having to resort to a sql-based schema format (sometimes you gotta be hardcore like that). It seems like Solid Queue doesn't like this setting, I end up with a blank queue_structure.sql file.

I have a sample repo here https://github.com/jherdman/baconator5k you can see the action played out in 3 commits.

**Comment by rosa** [comment]
Hey @jherdman, this looks like a bug in Rails 🤔  It seems very similar to https://github.com/rails/rails/issues/52829, but that one should have been fixed. However, I understand your `queue_schema.rb` was emptied when you ran `db:migrate`, no? Which seems exactly the same thing there...

**Comment by jherdman** [comment]
Yup! That definitely seems like the one. I'll close this in favour of the aforementioned. Thanks, as always, for being so responsive!
