### ISSUE TITLE
RFC: "Force enqueue" scheduled jobs

### ISSUE THREAD

**Issue by fgrehm** [rails/solid_queue#398]
_Apologies in advance if this is the wrong medium to discuss feature requests or if it has been discussed already elsewhere_ :sweat_smile:

-------

Hey peeps!

I'm wondering if there are any plans to easily force execution of a scheduled job to take place "now" instead of whatever time it was scheduled to run.

This is something I'm used to from Sidekiq and is specially useful in development / staging environments. Bonus points for adding the functionality to [mission_control-jobs](https://github.com/rails/mission_control-jobs) :rocket: 

Thanks in advance!

**Comment by rosa** [comment]
Hey @fgrehm! Yes, definitely the right medium for this, and this is very much on the plans for Mission Control in the very near future. I'm working now on it towards Mission Control v1.0, and it'll include this functionality 😊

**Comment by rosa** [comment]
Oops, I forgot to comment here! This was already added to Mission Control https://github.com/rails/mission_control-jobs/pull/199. If you update to the last version, you'll have it.
