### ISSUE TITLE
SolidQueue's tests Vs. my local environment

### ISSUE THREAD

**Issue by hms** [rails/solid_queue#400]
I'm about ready to push a PR to address resource constrained deployments. 

As part of testing my PR I'm finding the tests have some issues and if they are known issues and not limited to my environment I'd like to include with the PR. What I'm seeing:

- There are several tests generate a "RuntimeError: everything is broken", although the tests report as passing.  I'm pretty sure this is due to a Stubbed object not allowing a method and AppExcutor.handle_thread_error "getting involved" in a way that allows the exception to not fail the test.
- There are several tests generate various broken pipe errors in Interruptible.rb.  I've got code that handles all of the errors that I've encountered.

I'm running on a M series MacBookPro.  PostgreSQL and MySQL are running in docker as configured via bin/setup.  I have not made any other changes or adjustments to the environment.

Are these known issues that I should include in my PR or yet another case of "it's just me?"

**Comment by hms** [comment]
Adding to my confusion is .ruby-version is set at: 3.3.1, but the GitHub actions use ruby: 3.3.5.

What is the development standard for SolidQueue so I can match the expected requirements?

**Comment by rosa** [comment]
Oops, so sorry I haven't responded yet to this, I missed the notification last week!

> There are several tests generate a "RuntimeError: everything is broken", although the tests report as passing. 

Yes! This is expected, the error is raised on purpose. Setting `Thread.report_on_exception = false` prevents these from showing up at all in some cases but not all. 

> There are several tests generate various broken pipe errors in Interruptible.rb.

Huh, I haven't encountered those, but perhaps it's been by chance. I'm very curious to know what are the fixes. 

> Adding to my confusion is .ruby-version is set at: 3.3.1, but the GitHub actions use ruby: 3.3.5.

Ah, this is an oversight. Any of them should work, feel free to change `.ruby-version` to match GitHub actions if you want.

**Comment by hms** [comment]
@rosa Thanks again for all of your help.

Another question related to the tests (and their intent) to support a new PR:
SQ has tests for Exceptions raised in ClaimedExceptions.perform being reported up to the Rails.error handler.  I'm confused since the default SQ.on_thread_error defaults to:  
```config.solid_queue.on_thread_error ||= ->(exception) { Rails.error.report(exception, handled: false) }```

Wouldn't it make more sense to call Rails.error() IFF on_thread_error.nil? Otherwise, Exceptions are likely double reported.
