### ISSUE TITLE
What about adding jobs script to executables?

### ISSUE THREAD

**Issue by blocknotes** [rails/solid_queue#401]
Hey :)
In the gemspec, it could be useful something like:

```rb
  spec.bindir      = "exe"
  spec.executables = ["jobs"]
```

And the presence of the script in _exe_ path (updated to run also from the ruby bin path).
Useful to use it via _bundle exec_ for example.

What do you think?

**Comment by zarqman** [comment]
FYI, `jobs` is a standard unix binary (and internal command in some shells, IIRC), so if the gems binary dir is in the $PATH, this will conflict. It'd have to be renamed to something like `solid_queue` first.

**Comment by rosa** [comment]
Right now the `jobs` script is just to be copied over to your Rails app's `bin` directory, it's not intended to be run in any other way, so I'm not sure why this would be an advantage 🤔
