### ISSUE TITLE
Starting solid_queue on development erroring after upgrading Rails to 8.0

### ISSUE THREAD

**Issue by sebaherrera07** [rails/solid_queue#407]
I'm upgrading my web app to Rails 8.0, and it's a small app so I'm running the latest version of Ruby (3.3.6) and all gems. I also try to default to all autogenerated Rails configs as much as possible.

I already had Solid Queue up and running in `production` and `development` by calling `plugin :solid_queue` in `puma.rb`.

After upgrading Rails, when running `rails s` locally I'm getting the following error:
```
=> Booting Puma
=> Rails 8.0.0 application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 6.4.3 (ruby 3.3.6-p108) ("The Eagle of Durango")
*  Min threads: 3
*  Max threads: 3
*  Environment: development
*          PID: 38891
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
objc[39018]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[39018]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
Detected Solid Queue has gone away, stopping Puma...
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2024-11-11 19:01:44 -0300 ===
- Goodbye!
Exiting
```

If I run `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES rails s` it does work.

Any ideas what might be wrong with my setup?

**Comment by rosa** [comment]
Hey @sebaherrera07, are you using PostgreSQL in macOS? It sounds like a known bug with `pg` in macOS.

**Comment by lrjbrual** [comment]
I have the same issue, do you have any solution on this?

**Comment by rosa** [comment]
Yes https://github.com/rails/solid_queue/issues/167#issuecomment-2016992151
Going to close this one, I forgot!

**Comment by lrjbrual** [comment]
hi @rosa I still got this error, is that in pg issue? thanks

**Comment by rosa** [comment]
@lrjbrual do you get the error when setting this environment variable? 
```
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

And yes, it's an issue in the `pg` gem with macOS.

**Comment by sebaherrera07** [comment]
@lrjbrual @rosa I just edited a line in my first comment, because the command that works for me is with `bin/rails s`, no just `rails s`, so it's:
```
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES bin/rails s
```

**Comment by rosa** [comment]
Ahh @sebaherrera07, thank you and no worries! The environment variable is the important bit in any case.

**Comment by lrjbrual** [comment]
Yes, I use also bin/rails s. but is that issue is from PostgreSQL? I am thinking maybe it may cause issue in production.

**Comment by lrjbrual** [comment]
I wish we had the unix server. but no, we are using container for this project. but thanks, appreciate it, it seems working well.

**Comment by spaquet** [comment]
my few cents on this is that there are configurations that are not triggering the issue. I have an option source project https://github.com/spaquet/listopia where I use solid queue and when working on my Mac the issue does not trigger. I have an other Rails project where... the "same" configuration is triggering the issue.
I'm trying to figure out what part of the code is wrong and where we have differences that could explain why it's triggering this error.

**Comment by uhw76tgwquerhjbqwnejk** [comment]
is using `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` dangerous in production? I am planning to run production rails on  macOS and im running into this issue. Chat GPT warned me that this could cause unexpected crashes or other issues. I'm a total rails/ruby newbie so I am unsure if that is accurate or not.
