### ISSUE TITLE
How do we separate queues on different servers?

### ISSUE THREAD

**Issue by ratnarajsukale** [rails/solid_queue#413]
I have two queues:

1. **default**  
2. **live_updates**

I also have two VPS servers. I want to run these queues on different servers because their resource and priority requirements are different. 

The only command I found online is:

```bash
bundle exec rake solid_queue:start
```

Which i think will take any ready to execute job & not from any specific queue. 
I tried giving  ```--queue ``` flag but the container won't even start saying this flag won't work.
Then i tried ``-q`` flag, this will start the worker but takes jobs randomly.
Also is there any documentation for it that i missed?

**Comment by rosa** [comment]
Hey! You can use different config files and specify [which queues you want in each server](https://github.com/rails/solid_queue?tab=readme-ov-file#configuration).

```
bin/jobs --help
Commands:
  jobs help [COMMAND]  # Describe available commands or one specific command
  jobs start           # Starts Solid Queue supervisor to dispatch and perform enqueued jobs. Default command.

Options:
  -c, [--config-file=SOLID_QUEUE_CONFIG]                          # Path to config file (default: config/queue.yml).
      [--recurring-schedule-file=SOLID_QUEUE_RECURRING_SCHEDULE]  # Path to recurring schedule definition (default: config/recurring.yml).
      [--skip-recurring]                                          # Whether to skip recurring tasks scheduling
                                                                  # Default: false
```

**Comment by ratnarajsukale** [comment]
Hi, Thanks for the help, just realised i do not have ```bin/jobs```.  Then found out i was using ```gem "solid_queue", "~> 0.3.1"```  LOL!
