### ISSUE TITLE
Invalid Recurring Jobs: No Feedback

### ISSUE THREAD

**Issue by jherdman** [rails/solid_queue#414]
I recently added a new entry to `recurring.yml` and mistyped the name of the corresponding job class. I only realized something was askew when I viewed the Recurring Tasks tab in Mission Control.

I believe there ought to be some feedback when an invalid job class is listed. Perhaps an error or warning. This is something I'm happy to try and implement if it's of interest.

**Comment by rosa** [comment]
Indeed! This is on my personal backlog 😅 I just haven't been able to get to it. I wanted to do a general configuration validation, for recurring tasks but also for the rest of the configuration. If you want to try to implement it, even if it's just for recurring tasks, that'd be awesome!

**Comment by jherdman** [comment]
I'll give it a go! I'll have some time later this week.
