### ISSUE TITLE
Starting/Stopping Specific Workers for SolidQueue

### ISSUE THREAD

**Issue by bmb1603** [rails/solid_queue#418]
Currently, if I need to update the code for a single job, I find myself restarting the entire SolidQueue system, which disrupts all running jobs. Is there any guidance on how to:

1. Stop a worker for a specific queue.
2. Start (or restart) it without affecting other workers.

**Comment by rosa** [comment]
Hey @bmb1603, you can use signals to [terminate specific workers as described in the README](https://github.com/rails/solid_queue?tab=readme-ov-file#threads-processes-and-signals). However, I wouldn't recommend running mixed code between workers or updating code in production without deploying your app, and in most setups, if you deploy your app, the deployment would take care of restarting all your workers (or at least it should).

**Comment by bmb1603** [comment]
Thank you Rosa! So in other words SolidQueue should completely shutdown and restart with every new deployment? Which probably would happen automatically when using the whole pipeline with Kamal/etc.?

We are running SolidQueue as an Ubuntu Service. Sounds like this is the root of the issue then?

**Comment by rosa** [comment]
> So in other words SolidQueue should completely shutdown and restart with every new deployment?

Not just Solid Queue, but any Active Job backend, otherwise you might be running old code 🤔  You might want a short period to finish in-flight jobs, but eventually you'd need to restart it. 

With Kamal, depending on how you configure it, it should happen automatically, yes. You might want to check [`stop-wait-time`](https://kamal-deploy.org/v1/docs/configuration/overview/#stop-wait-time). 

I'm not sure about Ubuntu services or what the issue is 🤔  Is Solid Queue not getting restarted when you deploy or is it something else?

**Comment by jmarsh24** [comment]
![CleanShot 2024-11-22 at 16 43 44@2x](https://github.com/user-attachments/assets/59aadf3a-c6a1-4513-8a24-0d7146293153)
I'm running solid_queue in production with kamal. After a month or two of development I have ended up with pages of workers without knowing what to do with them. My concurrency is off the charts!

**Comment by rosa** [comment]
Huh, @jmarsh24, how has that happened? Are they all running because they've never been stopped? Running old code?

**Comment by rosa** [comment]
> Is there an easy way to prune these workers?

You could simply delete the records in the DB and they'd terminate when they realise their records are gone. However, if I were you, I'd try to find where the actual processes are running and why they weren't sent the proper signals to terminate when you deploy, and then I'd send them `TERM` signals. I think I'd ask about that in https://github.com/basecamp/kamal if you can't figure it out.

**Comment by jmarsh24** [comment]
I will also try to figure out why it's not being cleared, but could you please help me figure out how to get back to useable state? I tried running `SolidQueue::Process.delete_all`. Its look like the processes get deleted but then in the interface I still see them.
