### ISSUE TITLE
Recurring tasks ignored after separate the database.

### ISSUE THREAD

**Issue by facedo** [rails/solid_queue#431]
I am working with solid_queue in my 3 applications without any problem. In all of them i configured solid_queue tables in the main database (no separate connection).
Today, i added solid_cache and solid_cable to 1 of my applications with separate databases, and for better organization changed the database of solid_queue to its own database and making all the configurations in the manual.
All works fine, the messages from solid_cable are ok without redis, the jobs are managed perfect when they are performed by the application... But, the recurring tasks are ignored by solid_queue. The tables are created in the database but are empty. Initially i see that recurring where created/changed each time i changed the config/recurring.yml, but now it's not working and i had try everything and doesn't work.

**Comment by Halvanhelv** [comment]
Hi! @facedo you fixed this problem? how?
