### ISSUE TITLE
Question on Solid Queue job execution guarantees: at least once or exactly once?

### ISSUE THREAD

**Issue by doctomarculescu** [rails/solid_queue#432]
We are trying to understand what is the risk of executing non idempotent jobs in solid queue, precisely what is the risk of a job being executed twice in edge cases. 

Would it be possible to know if execution guarantees are "at least once" which are the cases when duplicated execution may happen? Or, if the execution model is guaranteed to be "exactly once" (failure counts for an execution), would it be possible to confirm it?

Many thanks,
Andrei

**Comment by doctomarculescu** [comment]
Thank you @rosa for the reply. So if I understand it correctly, only if we retry the jobs duplicated execution can happen. solid_queue won't move the jobs from claimed to ready in any case. So if we make sure only idempotent jobs are retried as part of our ActiveJob retry strategy, there is no risk a non idempotent job is reexecuted. Is my understanding correct?

**Comment by rosa** [comment]
Ah, sorry, forgot about a case: if you have a long-running job and you terminate Solid Queue (for example, for a deploy, where you need to restart the supervisor), but the long-running job doesn't finish within `shutdown_timeout`, then the interruption will happen before [this finishes](https://github.com/rails/solid_queue/blob/c521c6d47d10abeaf076a81d9af29e80eb2b11c7/app/models/solid_queue/claimed_execution.rb#L61), and in that case, the worker would have the chance to finish orderly and will move the job back to ready, so it'll be picked up by another worker. In this case, the job didn't finish, but it'll run again, so whatever it did the first run would potentially be repeated the next time it runs. 

To avoid this, you could make sure non-idempotent jobs never take longer than `shutdown_timeout`.

**Comment by doctomarculescu** [comment]
Thank you so much! I'll close this question, in case you think of any other edge case, it's still there :)

**Comment by rosa** [comment]
Sounds good, thanks so much! If you encounter any problems don't hesitate to let me know 🙏
