### ISSUE TITLE
Running solid_queue:install if already installed adds duplicate line in config/production.rb

### ISSUE THREAD

**Issue by joelzwarrington** [rails/solid_queue#440]
I've setup a new 8.0 rails project, and thought I might need to run the installation task solid_queue:install.

When running the install task, it did not modify any other files as they were identical, but did add a duplicate line to config/production.rb:

```ruby
config.solid_queue.connects_to = { database: { writing: :queue } }
```

**Comment by rosa** [comment]
Hey @joelzwarrington, I've fixed this in https://github.com/rails/solid_queue/pull/439 but haven't released the gem with that fix yet.

**Comment by joelzwarrington** [comment]
Thank you @rosa, that's awesome ❤️ 

Fixed by https://github.com/rails/solid_queue/pull/439
