### ISSUE TITLE
Setup development to work with solid_queue out of the box

### ISSUE THREAD

**Issue by joelzwarrington** [rails/solid_queue#441]
When starting a new 8.0 rails project it doesn't fully setup solid_queue as I might expect. 

It doesn't configure the following in development:
1. `active_job.queue_adapter`
2. `solid_queue.connects_to`
3. `config/database.yml`

It'd be nice if I could just start solid queue right away in development with a new Rails 8.0 project.

**Comment by rosa** [comment]
Related: https://github.com/rails/solid_queue/pull/390

**Comment by joelzwarrington** [comment]
Ahh, didn't see that one! Cheers.

Duplicate of https://github.com/rails/solid_queue/pull/390
