### ISSUE TITLE
Specify `source` of SolidQueue to ErrorReporter

### ISSUE THREAD

**Issue by tmimura39** [rails/solid_queue#446]
Because SolidQueue uses the [Rails executor](https://guides.rubyonrails.org/threading_and_code_execution.html#executor), exceptions raised in a Job are automatically handled by [ActiveSupport::ErrorReporter](https://guides.rubyonrails.org/error_reporting.html).

This is very convenient.
I want to make this even more convenient.

## Proposal

Simply put, this is what I propose.
```diff
diff --git a/lib/solid_queue/app_executor.rb b/lib/solid_queue/app_executor.rb
index da0976f..0580213 100644
--- a/lib/solid_queue/app_executor.rb
+++ b/lib/solid_queue/app_executor.rb
@@ -4,7 +4,7 @@ module SolidQueue
   module AppExecutor
     def wrap_in_app_executor(&block)
       if SolidQueue.app_executor
-        SolidQueue.app_executor.wrap(&block)
+        SolidQueue.app_executor.wrap(source: "application.solid_queue", &block)
       else
         yield
       end
```

Currently, the [default value](https://github.com/rails/rails/blob/v8.0.0/activesupport/lib/active_support/execution_wrapper.rb#L86) `application.active_support` is applied for source.
This does not identify it as an exception raised inside SolidQueue.

This is a quote from the [rails guide](https://guides.rubyonrails.org/error_reporting.html#error-reporting-options).
> source: a String about the source of the error. The default source is "application". Errors reported by internal libraries may set other sources; the Redis cache library may use "redis_cache_store.active_support", for instance. Your subscriber can use the source to ignore errors you aren't interested in.

Again, examples of the use of `source` were explained.
https://github.com/rails/rails/pull/44999

What do you think?

**Comment by rosa** [comment]
Ohh, this is a great suggestion! I didn't know this, somehow missed it! 😳 But it makes complete sense. Would you like to open a PR with this change?

**Comment by tmimura39** [comment]
Thanks for the response.

I'll do it today👍
