### ISSUE TITLE
Jobs being assigned to workers that are dead

### ISSUE THREAD

**Issue by strawhatduckk** [rails/solid_queue#455]
Hi folks, hoping to get a little insight here on why this might be happening.

I am seeing instances where the job is enqueued to workers where the worker's last heartbeat is earlier than the job enqueue time.

I've customized my heartbeat interval and alive threshold to values lower than default hoping that this would fix the issue, but it didn't help.

```rb
    # solidqueue config
    config.solid_queue.process_heartbeat_interval = 10.seconds
    config.solid_queue.process_alive_threshold = 60.seconds
```

Here's an example of a pruned job's raw data and the worker's last heartbeat. For the given example, the job last heartbeat is at `2024-12-16 05:23:44 UTC`, while the job was enqueued at `2024-12-16T05:23:45.606556697Z`.

![CleanShot 2024-12-16 at 1  32 01@2x](https://github.com/user-attachments/assets/3ea6a740-6753-4462-b6d5-cb2c8990ba45)

```rb
 {
  "id": 4011845750,
  "queue_name": <queue_name>,
  "class_name": <class_name>
  "arguments": {
    "job_class": <job_class_name>,
    "job_id": "1cde4c61-d5d2-4676-aa36-a6176c17bc7b",
    "provider_job_id": null,
    "queue_name": <queue_name>,
    "priority": 10000,
    "arguments": [
      {
        "id": 153578,
        "index": 1,
        "batch_size": 20,
        "job_id": 3,
        "_aj_ruby2_keywords": [
          "tenant_id",
          "library_id",
          "index",
          "batch_size",
          "job_id"
        ]
      }
    ],
    "executions": 0,
    "exception_executions": {
    },
    "locale": "en",
    "timezone": "UTC",
    "enqueued_at": "2024-12-16T05:23:45.606556697Z",
    "scheduled_at": "2024-12-16T05:23:45.606449907Z"
  },
  "priority": 10000,
  "active_job_id": "1cde4c61-d5d2-4676-aa36-a6176c17bc7b",
  "scheduled_at": "2024-12-16T05:23:45.606Z",
  "finished_at": null,
  "concurrency_key": null,
  "created_at": "2024-12-16T05:23:45.607Z",
  "updated_at": "2024-12-16T05:23:45.607Z"
}
```

**Comment by rosa** [comment]
Hmmm... I think these workers grab jobs correctly before their heartbeat actually expires. I think you need to find out why the workers stop sending heartbeats to fix this, rather than trying to work around it. What's killing your workers? 

> the worker's last heartbeat is at 2024-12-16 05:23:44 UTC, while the job was enqueued at 2024-12-16T05:23:45.606556697Z.

This is fine and expected, the heartbeat is updated every 10 seconds, and a worker is considered dead after 60 seconds from the last heartbeat with your settings: 
```ruby
    config.solid_queue.process_heartbeat_interval = 10.seconds
    config.solid_queue.process_alive_threshold = 60.seconds
```
So that worker is not dead or anything and could pick that job without any problems.

**Comment by strawhatduckk** [comment]
Thanks @rosa 

We have CD for the job workers that happen frequently throughout the app, so there might be a race condition between workers grabbing a job and receiving a signal to be killed - i wonder if theres anything we can do so that the jobs are picked up confidently.

**Comment by rosa** [comment]
@strawhatduckk what's CD? Continuous deployment? How are you deploying in such a way that workers are killed? They don't need to be killed. If [you send the proper signals](https://github.com/rails/solid_queue?tab=readme-ov-file#threads-processes-and-signals) (`TERM`), workers will try to finish whatever they're doing and if they can't finish, the jobs will be put back in the queue cleanly and picked back again.

**Comment by rosa** [comment]
You also shouldn't be signalling the workers directly, but the supervisor, to make sure things exit cleanly.

**Comment by strawhatduckk** [comment]
Got it, looks like we should change how we do things on our end.

Thanks for the help, @rosa.
