### ISSUE TITLE
Getting `Segmentation fault` error during solid queue initialization

### ISSUE THREAD

**Issue by BaggioGiacomo** [rails/solid_queue#458]
When I start my rails app the solid queue process crashes giving this error: `/Users/jack/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/pg-1.5.8/lib/pg/connection.rb:705: [BUG] Segmentation fault at 0x0000000128080b28`

Here's the crash report log information: https://pastebin.com/ZMjGYMhN

This is how I run the app (`Procfile.dev`):
```
web: bin/rails server
css: bin/rails tailwindcss:watch
solid_queue: bin/jobs
```

After getting this error, the solid queue process is running correctly.

## Gems
- pg: 1.5.8
- solid_queue: 1.1.0
- rails: 7.2.1.1
- ruby 3.3.4

Database is living inside a docker container.

**Comment by rosa** [comment]
This looks like this: https://github.com/rails/solid_queue/issues/145#issuecomment-1954024164
It's not a Solid Queue problem, but a problem with `pg` and macOS.

**Comment by BaggioGiacomo** [comment]
Yeah, I remember that. Since I haven't received this error in weeks I thought that it was fixed by solid queue

Is disabling a security parameter the best/only way to fix this?

**Comment by rosa** [comment]
I think so. Solid Queue can't fix this because it's a problem of the `pg` gem, it'd have to stop forking processes completely to not trigger the bug, but there's no way to fix it.
