### ISSUE TITLE
Random occurences of "unitialized constant" errors

### ISSUE THREAD

**Issue by mbajur** [rails/solid_queue#464]
Hello!
Since the very beginning of trying out solid_queue, I'm facing the same issue over and over again. There are two jobs in my app causing "Unitialized constant"exception. One of them is triggered by app and second one is defined as recurring task. From time to time, instead of run them, solid_queue raises `uninitialized constant <module name>` and the job is not being run. It's so random i can't really pinpoint what's so special about the jobs raising this because today it's one job and tomorrow that might be completely different one.

Natural place to start would be to check out what's special about the jobs that are failing but, as i mentioned, the choice of jobs failing is random and i can run them totally fine with `<MyJob>.perform_now` so they are fine i guess. It seems just like it's not anything with jobs but with solid_queue that randomly fails to autoload a constants for some reason. One more "predictable" way of causing that is to run scheduled jobs by hand - they will fail 90% of the time with unitialized constant error but 10% of cases will run just fine.

I don't even know what details to provide in here but let's start with that I'm on Rails 7.1.0 and solid_queue 1.0.2.

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the SolidQueue initialization to ensure proper constant loading and added a hook to reload constants before job execution.

You can review changes in this commit: https://github.com/wwqwq2313/rails-solid_queue-464/commit/dc8d8d8dde7da9619439e950d0321d8946b7f095.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by rosa** [comment]
@mbajur how are you running Solid Queue? 

> One more "predictable" way of causing that is to run scheduled jobs by hand - they will fail 90% of the time with unitialized constant error but 10% of cases will run just fine.

What do you mean with this exactly? What do you do to run these jobs "by hand"?

**Comment by mbajur** [comment]
Ah, right, sorry, i meant running them with "Run now" button in mission_control-jobs UI on the Recurring tasks tab.

I'm running solid_queue via kamal with `cmd: bin/jobs`

**Comment by rosa** [comment]
I haven't been able to reproduce anything similar to this 🤔 I think I'd need more information here, without a clear reproduction I can't investigate, I'm sorry.

**Comment by mbajur** [comment]
Ok, i moved to good_job and it's now solved so i think this issue might be closed as i don't have more details nor need for solution anymore. Thanks!
